### ISSUE TITLE
 java.lang.IllegalAccessError: class com.jidesoft.plaf.LookAndFeelFactory on Java 9

### ISSUE THREAD

**Issue by rakeshsrinivasa** [jidesoft/jide-oss#26]
Hi , 

I have upgraded jide-oss-3.7.1.jar and trying to run my java application (webstart and applet) in client system with Java 9. But i am getting below error 

Exception in thread "AWT-EventQueue-2" java.lang.IllegalAccessError: class com.jidesoft.plaf.LookAndFeelFactory (in unnamed module @0x2218f972) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x2218f972
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
....

Can some one help me ,how to fix this

**Comment by hiro0107** [comment]
Once I upgraded JDK to 9, I met the same issue.
My OS is Windows7.

**Comment by ctkemper** [comment]
Two solutions:
1) Set this system property:
 ` -Djide.defaultStyle=1`
2) Call this before creating any jide components: 
 ` LookAndFeelFactory.installJideExtension(LookAndFeelFactory.EXTENSION_STYLE_VSNET);`
