### ISSUE TITLE
Unhandled error when parsing Aqua Preferences on Mac OSX Big Sur

### ISSUE THREAD

**Issue by raducoravu** [jidesoft/jide-oss#47]
On Big Sur run with Java 1.8 or 15 the JIDE code throws an error when parsing part of the Aqua Preferences file:

      java.io.IOException: parseInt: unsupported byte count:16
	at com.jidesoft.plaf.aqua.BinaryPListParser.parseInt(BinaryPListParser.java:673)
	at com.jidesoft.plaf.aqua.BinaryPListParser.parseObjectTable(BinaryPListParser.java:424)
	at com.jidesoft.plaf.aqua.BinaryPListParser.parse(BinaryPListParser.java:310)
	at com.jidesoft.plaf.aqua.AquaPreferences.readPList(AquaPreferences.java:134)
	at com.jidesoft.plaf.aqua.AquaPreferences.loadGlobalPreferences(AquaPreferences.java:90)
	at com.jidesoft.plaf.aqua.AquaPreferences.get(AquaPreferences.java:62)
	at com.jidesoft.plaf.aqua.AquaPreferences.getString(AquaPreferences.java:56)
	at com.jidesoft.plaf.aqua.AquaJideUtils.isGraphite(AquaJideUtils.java:485)

**Comment by vtummal** [comment]
Hello @raducoravu 
Did you find a resolution to your issue? I have the exact same problem with my application after upgrade to Big Sur.
Thanks!

**Comment by raducoravu** [comment]
@vtummal I patched the class BinaryPListParser and created our custom build of the Jide jar. But I'm not sure if the patch is correct, it just hides the error so this is why I did not propose a fix.
